from django.urls import path

from .views import (
    rental_schedule_view,
    dashboard_view,
    payment_verification_view,
    rental_history_view,
    security_deposits_view,
    receipt_records_view,
    active_reservations_view,
    pending_approval_view,
    gown_catalog_view,
    gown_status_update_view,
    gown_delete_view,
    gown_create_view,
    gown_photo_update_view,
    gown_block_create_view,
    gown_block_delete_view,
    reservation_approve_view,
    reservation_reject_view,
    reservation_return_deposit_view,
    reservation_item_mark_returned_view,
    reservation_item_reschedule_view,
    categories_view,
    clients_view,
    staff_management_view,
    staff_create_view,
    staff_update_view,
    staff_toggle_status_view,
    staff_delete_view,
    admin_login_view,
    admin_logout_view,
    page_view,
    save_profile_view,
    upload_profile_picture_view,
    remove_profile_picture_view,
    update_avatar_position_view,
    admin_search_view,
    customer_flag_view,
)

app_name = "arabela_admin"

urlpatterns = [
    path("admin-login/", admin_login_view, name="admin_login"),
    path("logout/", admin_logout_view, name="admin_logout"),
    path("", dashboard_view, name="dashboard"),
    path("rental-schedule/", rental_schedule_view, name="rental_schedule"),
    path("calendar/", rental_schedule_view, name="calendar"),
    path("payment-verification/", payment_verification_view, name="payment_verification"),
    path("rental-history/", rental_history_view, name="rental_history"),
    path("security-deposits/", security_deposits_view, name="security_deposits"),
    path("receipt-records/", receipt_records_view, name="receipt_records"),
    path("active-reservations/", active_reservations_view, name="active_reservations"),
    path("pending-approval/", pending_approval_view, name="pending_approval"),
    path("gown-catalog/", gown_catalog_view, name="gown_catalog"),
    path("api/gowns/", gown_create_view, name="gown_create"),
    path("api/gowns/<int:gown_id>/status/", gown_status_update_view, name="gown_status_update"),
    path("api/gowns/<int:gown_id>/delete/", gown_delete_view, name="gown_delete"),
    path("api/gowns/<int:gown_id>/photo/", gown_photo_update_view, name="gown_photo_update"),
    path("api/gowns/<int:gown_id>/block-dates/", gown_block_create_view, name="gown_block_create"),
    path("api/gown-blocks/<int:block_id>/delete/", gown_block_delete_view, name="gown_block_delete"),
    path("api/reservations/<int:pk>/approve/", reservation_approve_view, name="reservation_approve"),
    path("api/reservations/<int:pk>/reject/", reservation_reject_view, name="reservation_reject"),
    path("api/reservations/<int:pk>/return-deposit/", reservation_return_deposit_view, name="reservation_return_deposit"),
    path("api/reservation-items/<int:item_id>/mark-returned/", reservation_item_mark_returned_view, name="reservation_item_mark_returned"),
    path("api/reservation-items/<int:item_id>/reschedule/", reservation_item_reschedule_view, name="reservation_item_reschedule"),
    path("categories/", categories_view, name="categories"),
    path("clients/", clients_view, name="clients"),
    path("api/customers/<int:user_id>/flag/", customer_flag_view, name="customer_flag"),
    path("staff-management/", staff_management_view, name="staff_management"),
    path("api/staff/", staff_create_view, name="staff_create"),
    path("api/staff/<int:user_id>/update/", staff_update_view, name="staff_update"),
    path("api/staff/<int:user_id>/status/", staff_toggle_status_view, name="staff_toggle_status"),
    path("api/staff/<int:user_id>/delete/", staff_delete_view, name="staff_delete"),
    path("save-profile/", save_profile_view, name="save_profile"),
    path("api/profile-picture/", upload_profile_picture_view, name="upload_profile_picture"),
    path("api/profile-picture/remove/", remove_profile_picture_view, name="remove_profile_picture"),
    path("api/profile-picture/position/", update_avatar_position_view, name="update_avatar_position"),
    path("api/search/", admin_search_view, name="admin_search"),
    path("<str:page>.html", page_view, name="page"),
]
