# Generated by Django 6.0.3 on 2026-07-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gowns', '0003_alter_gown_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Cash', 'Cash')], max_length=10)),
                ('payment_proof_url', models.URLField(blank=True)),
                ('rental_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gown_name', models.CharField(max_length=150)),
                ('gown_slug', models.CharField(blank=True, max_length=150)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('gown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_items', to='gowns.gown')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation')),
            ],
            options={
                'ordering': ['rental_date'],
            },
        ),
    ]
