# Generated by Django 6.0.3 on 2026-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='picked_up_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='stage',
            field=models.CharField(choices=[('Awaiting Pickup', 'Awaiting Pickup'), ('Picked Up', 'Picked Up'), ('Returned', 'Returned')], default='Awaiting Pickup', max_length=20),
        ),
    ]
