# Generated by Django 6.0.3 on 2026-07-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationitem_picked_up_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='stage',
            field=models.CharField(choices=[('Pick-up', 'Pick-up'), ('Reserved', 'Reserved'), ('Return', 'Return'), ('Overdue', 'Overdue'), ('Returned', 'Returned')], default='Pick-up', max_length=20),
        ),
    ]
