# Generated by Django 6.0.3 on 2026-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remap_legacy_stage_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='overdue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
