# Generated by Django 6.0.3 on 2026-07-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservationitem_overdue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationitem',
            name='overdue_date',
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
