# Generated by Django 6.0.3 on 2026-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_backfill_event_date_reset_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='overdue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
