# Generated by Django 6.0.3 on 2026-07-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_backfill_overdue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='return_condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Needs Repair', 'Needs Repair')], max_length=20),
        ),
    ]
