# Generated by Django 6.0.3 on 2026-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_address_reservation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
