# Generated by Django 6.0.3 on 2026-09-12 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservationitem_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('actor', models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('System', 'System')], default='System', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_known', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='reservations.reservationitem')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='reservations.reservation')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['reservation', 'occurred_at'], name='reservation_reserva_4d6c94_idx')],
            },
        ),
    ]
