# Generated by Django 6.0.3 on 2026-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_backfill_status_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_on', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
