# Generated by Django 6.0.3 on 2026-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reminderrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
