# Generated by Django 6.0.3 on 2026-09-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_receiptrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='original_rental_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='original_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
