# Generated by Django 6.0.3 on 2026-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_backfill_original_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationstatusevent',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
