# Generated by Django 6.0.3 on 2026-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_reservationstatusevent_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gcash_reference',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=20),
        ),
    ]
