# Generated by Django 6.0.3 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
