# Generated by Django 6.0.3 on 2026-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reservations_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
