# Generated by Django 6.0.3 on 2026-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_reservations_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_position_x',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_position_y',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
