# Generated by Django 6.0.3 on 2026-07-23 12:11

from django.db import migrations, models


def grandfather_existing_admins_to_owner(apps, schema_editor):
    """Anyone who already had admin access before roles existed (is_staff or
    is_superuser) was effectively a full-access admin, so grandfather them to
    OWNER -- this keeps the current owner from being locked out of Staff
    Management. Only accounts created AFTER this migration, through the new
    staff-creation flow, get the restricted Manager/Staff role. A UserProfile is
    created for any such admin that somehow lacks one."""
    UserModel = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in UserModel.objects.filter(is_staff=True) | UserModel.objects.filter(is_superuser=True):
        profile, _ = UserProfile.objects.get_or_create(user=user)
        if profile.role != 'Owner':
            profile.role = 'Owner'
            profile.save(update_fields=['role'])


def noop_reverse(apps, schema_editor):
    # Roles were purely additive; nothing to undo on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_avatar_position_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=10),
        ),
        migrations.RunPython(grandfather_existing_admins_to_owner, noop_reverse),
    ]
