# Generated by Django 6.0.3 on 2026-07-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hold_abandon_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
