# Generated by Django 6.0.3 on 2026-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_hold_abandon_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
