# Generated by Django 6.0.3 on 2026-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_cart_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='category',
            field=models.CharField(choices=[('Account Flagged', 'Account Flagged'), ('Account Unflagged', 'Account Unflagged'), ('Reservation Reminder', 'Reservation Reminder'), ('Return Overdue', 'Return Overdue'), ('General', 'General')], default='General', max_length=30),
        ),
    ]
