# Generated by Django 6.0.3 on 2026-09-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customermessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cancel_tier1_lockout_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cancel_tier2_lockout_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='category',
            field=models.CharField(choices=[('Account Flagged', 'Account Flagged'), ('Account Unflagged', 'Account Unflagged'), ('Reservation Reminder', 'Reservation Reminder'), ('Return Overdue', 'Return Overdue'), ('Cancellation Lockout', 'Cancellation Lockout'), ('General', 'General')], default='General', max_length=30),
        ),
    ]
