# Generated by Django 6.0.3 on 2026-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_cancel_lockout_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
