# Generated by Django 6.0.3 on 2026-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gown_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Wedding', 'Wedding'), ('Ball', 'Ball'), ('Thailand', 'Thailand'), ('Bridesmaid', 'Bridesmaid'), ('Sexy', 'Sexy'), ('Ninang', 'Ninang'), ('Filipiniana', 'Filipiniana'), ('Suit', 'Suit'), ('Flower Girl', 'Flower Girl'), ('Belo', 'Belo'), ('Coat', 'Coat'), ('Guest', 'Guest')], max_length=20)),
                ('color_name', models.CharField(max_length=40)),
                ('color_code', models.CharField(max_length=2)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large'), ('Free Size', 'Free Size')], max_length=20)),
                ('design_variant', models.CharField(blank=True, max_length=60)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('In-Cleaning', 'In-Cleaning'), ('Out-of-Stock', 'Out-of-Stock')], default='Available', max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_returned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'color_code', 'gown_id'],
            },
        ),
    ]
