# Generated by Django 6.0.3 on 2026-07-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0002_alter_gown_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='category',
            field=models.CharField(choices=[('Wedding Gown', 'Wedding Gown'), ('Ball Gown', 'Ball Gown'), ('Sexy Gown', 'Sexy Gown'), ('Ninang Gown', 'Ninang Gown'), ('Suit', 'Suit'), ('Filipiniana', 'Filipiniana'), ('Guest Gown', 'Guest Gown'), ('Flower Girl', 'Flower Girl'), ('Belo', 'Belo'), ('Thailand Gown', 'Thailand Gown')], max_length=20),
        ),
    ]
