# Generated by Django 6.0.3 on 2026-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0004_alter_gown_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/share/1EHAS1iemQ/')),
                ('phone', models.CharField(blank=True, default='09635215485', max_length=20)),
                ('shop_street', models.CharField(blank=True, default='3rd Flr Park Place Bldg Centre', max_length=150)),
                ('shop_city', models.CharField(blank=True, default='Antipolo', max_length=100)),
                ('shop_country', models.CharField(blank=True, default='Philippines', max_length=100)),
                ('shop_postal_code', models.CharField(blank=True, default='1830', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
