# Generated by Django 6.0.3 on 2026-07-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GownUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Alteration', 'Alteration'), ('Other', 'Other')], default='Cleaning', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='gowns.gown')),
            ],
            options={
                'verbose_name': 'gown unavailability',
                'verbose_name_plural': 'gown unavailabilities',
                'ordering': ['start_date', 'id'],
            },
        ),
    ]
