# Generated by Django 6.0.3 on 2026-08-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0006_gownunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
