# Generated by Django 6.0.3 on 2026-09-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0008_remove_gown_in_cleaning_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GownSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('color_code', models.CharField(max_length=2)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'color_code'), name='unique_gown_sequence_group')],
            },
        ),
    ]
