# Generated by Django 6.0.3 on 2026-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0010_backfill_gown_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='GownSlugSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=160, unique=True)),
                ('next_suffix', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
