# Generated by Django 6.0.3 on 2026-09-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0013_alter_gown_category'),
        ('reservations', '0021_reservationstatusevent_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='gownunavailability',
            name='auto_for_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_cooldown_block', to='reservations.reservationitem'),
        ),
        migrations.AlterField(
            model_name='gownunavailability',
            name='reason',
            field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Repair', 'Repair'), ('Alteration', 'Alteration'), ('Cooldown', 'Cooldown'), ('Other', 'Other')], default='Cleaning', max_length=20),
        ),
    ]
