# Generated by Django 6.0.3 on 2026-09-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0015_backfill_cooldown_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='category',
            field=models.CharField(choices=[('Wedding Gown', 'Wedding Gown'), ('Ball Gown', 'Ball Gown'), ('Long Gown', 'Long Gown'), ('Luxury Gown', 'Luxury Gown'), ('Mother Gown', 'Mother Gown'), ('Suit', 'Suit'), ('Filipiniana', 'Filipiniana'), ('Guest Gown', 'Guest Gown'), ('Flower Girl', 'Flower Girl'), ('Belo', 'Belo'), ('Thailand Gown', 'Thailand Gown'), ('Dresses', 'Dresses'), ('Kids Gown', 'Kids Gown'), ('Barong', 'Barong'), ('Ball Gown Tulle', 'Ball Gown Tulle')], max_length=20),
        ),
    ]
