# Generated by Django 6.0.3 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0016_alter_gown_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gown',
            name='category',
            field=models.CharField(choices=[('Wedding Gown', 'Wedding Gown'), ('Ball Gown', 'Ball Gown'), ('Long Gown', 'Long Gown'), ('Luxury Gown', 'Luxury Gown'), ('Mother Gown', 'Mother Gown'), ('Suit', 'Suit'), ('Filipiniana', 'Filipiniana'), ('Guest Gown', 'Guest Gown'), ('Dresses', 'Dresses'), ('Kids Gown', 'Kids Gown'), ('Barong', 'Barong'), ('Ball Gown Tulle', 'Ball Gown Tulle'), ('Bridesmaid Dresses', 'Bridesmaid Dresses')], max_length=20),
        ),
    ]
