# Generated by Django 6.0.3 on 2026-09-30 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0017_alter_gown_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gown',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gown',
            name='last_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_tag_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='gownsequence',
            name='color_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='GownRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gown_id', models.CharField(db_index=True, max_length=40)),
                ('tracking_number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('color_name', models.CharField(blank=True, max_length=40)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('photo_url', models.URLField(blank=True)),
                ('reason', models.CharField(choices=[('Damaged', 'Damaged beyond repair'), ('Lost or stolen', 'Lost or stolen'), ('Retired', 'Retired (sold or no longer offered)'), ('Other', 'Other')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('removed_by_name', models.CharField(blank=True, max_length=150)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('removed_at'), descending=True, nulls_last=True), '-id'],
            },
        ),
    ]
