# Generated by Django 6.0.3 on 2026-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0018_tag_colors_removal_log_and_gown_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='gcash_account_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gcash_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gcash_qr_url',
            field=models.URLField(blank=True, db_default='', default='', max_length=500),
        ),
    ]
