# Generated by Django 6.0.3 on 2026-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0020_custom_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategory',
            name='audience',
            field=models.CharField(choices=[('women', "Women's collection"), ('men', "Men's collection")], db_default='women', default='women', max_length=5),
        ),
    ]
