# Generated by Django 6.0.3 on 2026-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gowns', '0022_hidden_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('storage_name', models.CharField(blank=True, db_default='', default='', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
