"""
Django settings for arabela_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is a dev-only placeholder (the original hardcoded value,
# already public in this repo's git history) -- any real deployment must set
# SECRET_KEY in its own environment rather than rely on it.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-3(u%*fi*=6nbx5x6x=rvvfca$vh3b#n#cjp3h&q^0taoxp4p5e')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False -- a host that doesn't explicitly set DEBUG=True in its
# environment gets the safe production behavior automatically.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # Arabela apps
    'gowns',
    'reservations',
    'accounts',
    'ai_recommendation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files directly from the app process -- needed once
    # DEBUG=False, since Django's dev-server auto-serving of static files only
    # ever worked because DEBUG was True. No separate static file host required.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'arabela_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gowns.context_processors.featured_search_items',
                'gowns.context_processors.active_reservations_count',
                'gowns.context_processors.unread_messages_count',
                'gowns.context_processors.reservation_hold',
                'gowns.context_processors.site_settings',
                'arabela_admin.context_processors.admin_user',
                'arabela_admin.context_processors.admin_notifications',
                'arabela_admin.context_processors.admin_asset_version',
                'arabela_admin.context_processors.site_asset_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'arabela_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database credentials come from `.env` (see `.env.example`). Hardcoding them in
# this file risks committing secrets. Supabase: prefer Session pooler (same host,
# port 5432, user postgres.<ref>) over Transaction pool (6543) for Django; use the
# direct host db.<ref>.supabase.co only if your network resolves it (often IPv6).
_db_name = os.getenv('DATABASE_NAME', 'postgres')
_db_user = os.getenv('DATABASE_USER', '')
_db_password = os.getenv('DATABASE_PASSWORD', '')
_db_host = os.getenv('DATABASE_HOST', '')
_db_port = os.getenv('DATABASE_PORT', '5432')

if _db_host and _db_user and _db_password:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_name,
            'USER': _db_user,
            'PASSWORD': _db_password,
            'HOST': _db_host,
            'PORT': _db_port,
            'CONN_MAX_AGE': 0,
            'OPTIONS': {'sslmode': 'require'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Where `collectstatic` gathers everything for WhiteNoise to serve -- only
# matters once deployed; local `runserver` never touches this directory.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Media uploads (gown photos, GCash proof-of-payment, profile pictures) go to
# Cloudinary when it's configured -- Render's own disk is wiped on every
# restart/redeploy, which would otherwise silently delete every uploaded file.
# Falls back to local disk storage when no Cloudinary env vars are set (e.g.
# a fresh checkout with no `.env` yet), so local dev keeps working either way.
_cloudinary_cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME', '').strip()

if _cloudinary_cloud_name:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': _cloudinary_cloud_name,
        'API_KEY': os.getenv('CLOUDINARY_API_KEY', '').strip(),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', '').strip(),
    }
    _default_file_storage = 'cloudinary_storage.storage.MediaCloudinaryStorage'
else:
    _default_file_storage = 'django.core.files.storage.FileSystemStorage'

STORAGES = {
    "default": {"BACKEND": _default_file_storage},
    # Compressed (gzip/brotli) but NOT the Manifest variant -- Manifest storage
    # hard-fails `collectstatic` if any {% static %} tag anywhere points at a
    # file that doesn't exist, which is too strict a first deploy to risk. The
    # admin bundle.js/site JS already have their own `?v=` cache-busting (see
    # admin_asset_version/site_asset_version), so content-hashed filenames
    # aren't needed for that problem to already be solved.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Media files (gown photos, GCash screenshots). MEDIA_URL/MEDIA_ROOT only
# matter for the FileSystemStorage fallback above -- Cloudinary ignores them
# and serves its own URLs instead.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Required once the site is reachable over HTTPS on a real domain -- without
# its own scheme+host listed here, Django rejects every POST (login, reservation
# submit, admin actions) as a CSRF failure. Empty locally on purpose; set to
# e.g. "https://yourapp.onrender.com" in that host's environment variables.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

SITE_ID = 2

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = 'gowns:homepage'
LOGOUT_REDIRECT_URL = 'accounts:login'
LOGIN_URL = 'accounts:login'

# allauth account settings
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False

# allauth social settings
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.ArabelaSocialAccountAdapter'
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        },
    }
}

# Session "remember me" duration (seconds)
REMEMBER_ME_AGE = int(os.getenv('REMEMBER_ME_AGE', '1209600'))

# Outgoing email (verification + password reset)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
_env_default_from = os.getenv('DEFAULT_FROM_EMAIL', '').strip()
if not _env_default_from:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'no-reply@arabela.local'
elif _env_default_from == 'Arabela <no-reply@arabela.local>' and EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = f'Arabela <{EMAIL_HOST_USER}>'
elif _env_default_from == 'no-reply@arabela.local' and EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    DEFAULT_FROM_EMAIL = _env_default_from

# Arabela Recommends -- AI chat (Google Gemini, free tier).
# NOT 'gemini-flash-latest': that alias currently resolves to gemini-3.6-flash,
# whose free tier allows only 20 requests PER DAY and which burns ~800 output
# tokens "thinking" before answering (4-11s per reply). flash-lite answers the
# same questions in ~1.2s with no thinking overhead and a far larger free quota.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '').strip()
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-3.1-flash-lite')
